const Songlist=[
    {songUrl : "https://music.youtube.com/watch?v=Fm-vIlWcdPE", name:"DARLING JATT DI", dir:"Amrinder Gill, Gurlez Akhtar & Dr Zeus", views:"10M views", image:"https://i.ytimg.com/vi/Fm-vIlWcdPE/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3mclZdyHOCMSE2vLzRikri2ePEh8A"},
    {songUrl : "https://music.youtube.com/watch?v=Nr25SsJfZ8s", name:"Talashi", dir:"Street Boy, Mankirt Aulakh & Gurlez Akhtar", views:"15M views", image:"https://i.ytimg.com/vi/Nr25SsJfZ8s/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3loAe39VeaCIU2xB3yt5MLQNBDRyw"},
    {songUrl : "https://music.youtube.com/watch?v=pKwNDsBxXRA", name:"Qaafirana", dir:"Arijit Singh & Nikhita Gandhi", views:"87M views", image:"https://i.ytimg.com/vi/pKwNDsBxXRA/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3kUJhnvxXP5gUXvdrHGRh-2jatSyw"},
    {songUrl : "https://music.youtube.com/watch?v=tpovqQ2EkA4", name:"Gabru Gulab Warga", dir:"Gurnam Bhullar", views:"28M views", image:"https://i.ytimg.com/vi/tpovqQ2EkA4/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3kDUYhMKicRebw9c8HXMWnmGBi5hA"},
    {songUrl : "https://music.youtube.com/watch?v=uPl_jL9mCKc", name:"Koka", dir:"Mankirt Aulakh & Simar Kaur", views:"190M views", image:"https://i.ytimg.com/vi/uPl_jL9mCKc/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3l9xK4g7dwZUMzWvmV683wdTalETw"},
    {songUrl : "https://music.youtube.com/watch?v=IhFKziOD72g", name:"Khokhe", dir:"Mankirt Aulakh & SIMAR KAUR  ", views:"37M views", image:"https://i.ytimg.com/vi/IhFKziOD72g/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3k55Nhvz8hE8iNRAtHanWkr4Ttu_Q"}, 
]   
const Audiolist=[
    {songUrl : "https://music.youtube.com/watch?v=uChhQpHMmXE", name:"Aaye Haaye", dir:"Single", views:" Karan Aujla", image:"https://lh3.googleusercontent.com/mTs-Ui8p2HE28egPEfqLL_wMLb3ZqacpnlLLeSCsWXnz4W7uzdA1MBkjY0npm-xcMnIDyU15GBsyDjs=w120-h120-l90-rj"},
    {songUrl : "https://music.youtube.com/watch?v=WgVLjwyuk64", name:"Sorry", dir:"Single", views:"Mankirt Aulakh", image:"https://lh3.googleusercontent.com/5Dt-DtTL_TLW6uv4NeIMh4MD9s2v3tloOwqbLTL6SKsG1HnSTTMZWNYma64a2ntcs2bOqbA4cLxsD_ZO=w120-h120-l90-rj"},
    {songUrl : "https://music.youtube.com/watch?v=7A9VHHzWV1g", name:"Not Sure", dir:"Single", views:"Cheema Y & Gur Sidhu", image:"https://lh3.googleusercontent.com/qwmmCBO0h61huFqRPJYK-u78cTER5iEN_BocbJNck6AqKswZljOkMqEfD3hoLZXKQGKqWiKMQRIGayM=w120-h120-l90-rj"},
    {songUrl : "https://music.youtube.com/watch?v=tpovqQ2EkA4", name:"Gabru Gulab Warga", dir:"Gurnam Bhullar", views:"28M views", image:"https://i.ytimg.com/vi/tpovqQ2EkA4/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3kDUYhMKicRebw9c8HXMWnmGBi5hA"},
    {songUrl : "https://music.youtube.com/watch?v=QcND7dhD454", name:"Rangeen", dir:"Single", views:" Gurnam Bhullar", image:"https://lh3.googleusercontent.com/XyEvdStmOmJ5W17jJol62q7MMN4yzZf8AYToJ_tgXp_R2oLk__i2ofEy8uXNM5u9YCQciFFaUZNM5B3H=w120-h120-l90-rj"},
    {songUrl : "https://music.youtube.com/watch?v=XPKry_UABq8", name:"Hood Luv", dir:"Single", views:"Inder Chahal, Gurlez Akhtar & Amber", image:"https://lh3.googleusercontent.com/fndAKpQHvqzMOMLi6Xv9MYuXRv7s-dAnr7i3J5Ylih32y2V6x9mCjqT-lBcJzFznKXneBItrw18I7YhwYQ=w120-h120-l90-rj"},
    {songUrl : "https://music.youtube.com/watch?v=xju0lYqUJBo", name:"Dior", dir:"Single", views:"Pranjal Dahiya", image:"https://lh3.googleusercontent.com/KPquCjCIKnAlgKHvY2P1Jc9MnzHRpyNwUsz55HhO-i-lIsk4NSYyQliYlS_FCXasyQ2C2xXDa7RHAjs=w120-h120-l90-rj"},
    {songUrl : "https://music.youtube.com/watch?v=-97G7C5_Y4A", name:"Experimento", dir:"Album", views:"Saabi Bhinder", image:"https://lh3.googleusercontent.com/7qMMDOE1bl7yPIv3KACLuF7Al7TWNalgG0_y1K6EF6XHdHxAcC_D66pRb4Zer9aJ9hnC-l0-xUDu6Z6heQ=w120-h120-l90-rj"},
    {songUrl : "https://music.youtube.com/watch?v=lPs5RkyGNfk", name:"Befikre", dir:"EP", views:"Luv Athwal & Simar Kaur", image:"https://lh3.googleusercontent.com/At1LbWQ6xyylFNziUWGJXQhnB8VOiiS3g1FouxyJB3sVVDDnPKOU5QWFEfUic3PvzJR2FjY8cNsyUe4HfQ=w120-h120-l90-rj"},
] 
export {Songlist, Audiolist}
